# coding: utf-8

"""
    Stakeholder engagement API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import iengage-client
from iengage-client.rest import ApiException
from iengage-client.models.verve_response_notification_list import VerveResponseNotificationList


class TestVerveResponseNotificationList(unittest.TestCase):
    """ VerveResponseNotificationList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerveResponseNotificationList(self):
        """
        Test VerveResponseNotificationList
        """
        model = iengage-client.models.verve_response_notification_list.VerveResponseNotificationList()


if __name__ == '__main__':
    unittest.main()
