# coding: utf-8

"""
    Stakeholder engagement API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import iengage-client
from iengage-client.rest import ApiException
from iengage-client.models.verve_response_interaction_category_list import VerveResponseInteractionCategoryList


class TestVerveResponseInteractionCategoryList(unittest.TestCase):
    """ VerveResponseInteractionCategoryList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerveResponseInteractionCategoryList(self):
        """
        Test VerveResponseInteractionCategoryList
        """
        model = iengage-client.models.verve_response_interaction_category_list.VerveResponseInteractionCategoryList()


if __name__ == '__main__':
    unittest.main()
