# coding: utf-8

"""
    iEngage 2.0 API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import iengage_client
from iengage_client.rest import ApiException
from iengage_client.apis.rewards_api import RewardsApi


class TestRewardsApi(unittest.TestCase):
    """ RewardsApi unit test stubs """

    def setUp(self):
        iengage_client.configuration.access_token = None
        self.api = iengage_client.apis.rewards_api.RewardsApi()

    def tearDown(self):
        pass

    def test_get_top_friends(self):
        """
        Test case for get_top_friends

        Get list of top friends
        """
        requesterId = None
        clientToken = None
        uid = 532893
        start  =0
        end =10
        print(self.api.get_top_friends(uid,start,end,requesterId,clientToken))
        pass

    def test_get_top_users(self):
        """
        Test case for get_top_users

        Get list of top users
        """
        requesterId = None
        clientToken = None
        start  = 0
        end = 10
        print(self.api.get_top_users(start,end,requesterId,clientToken))
        pass


    def test_get_user_points(self):
        """
        Test case for get_user_points

        Get list of user points
        """
        requesterId = None
        clientToken = None
        uid = 532893
        print(self.api.get_user_points(uid,requesterId,clientToken))
        pass


if __name__ == '__main__':
    unittest.main()
