# coding: utf-8

"""
    Stakeholder engagement API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import iengage-client
from iengage-client.rest import ApiException
from iengage-client.models.verve_response_request_for_me_list import VerveResponseRequestForMeList


class TestVerveResponseRequestForMeList(unittest.TestCase):
    """ VerveResponseRequestForMeList unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerveResponseRequestForMeList(self):
        """
        Test VerveResponseRequestForMeList
        """
        model = iengage-client.models.verve_response_request_for_me_list.VerveResponseRequestForMeList()


if __name__ == '__main__':
    unittest.main()
