# coding: utf-8

"""
    Stakeholder engagement API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import iengage-client
from iengage-client.rest import ApiException
from iengage-client.models.blog import Blog


class TestBlog(unittest.TestCase):
    """ Blog unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlog(self):
        """
        Test Blog
        """
        model = iengage-client.models.blog.Blog()


if __name__ == '__main__':
    unittest.main()
