# coding: utf-8

"""
    Stakeholder engagement API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import iengage-client
from iengage-client.rest import ApiException
from iengage-client.models.idea_user_rating import IdeaUserRating


class TestIdeaUserRating(unittest.TestCase):
    """ IdeaUserRating unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdeaUserRating(self):
        """
        Test IdeaUserRating
        """
        model = iengage-client.models.idea_user_rating.IdeaUserRating()


if __name__ == '__main__':
    unittest.main()
