# coding: utf-8

"""
    Stakeholder engagement API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WFTask(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, task_id=None, name=None, description=None, transition_list=None, type=None, entity_id=None, due_date=None, attributes=None, entity=None):
        """
        WFTask - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'task_id': 'int',
            'name': 'str',
            'description': 'str',
            'transition_list': 'list[str]',
            'type': 'str',
            'entity_id': 'int',
            'due_date': 'datetime',
            'attributes': 'str',
            'entity': 'object'
        }

        self.attribute_map = {
            'task_id': 'taskId',
            'name': 'name',
            'description': 'description',
            'transition_list': 'transitionList',
            'type': 'type',
            'entity_id': 'entityId',
            'due_date': 'dueDate',
            'attributes': 'attributes',
            'entity': 'entity'
        }

        self._task_id = task_id
        self._name = name
        self._description = description
        self._transition_list = transition_list
        self._type = type
        self._entity_id = entity_id
        self._due_date = due_date
        self._attributes = attributes
        self._entity = entity

    @property
    def task_id(self):
        """
        Gets the task_id of this WFTask.

        :return: The task_id of this WFTask.
        :rtype: int
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """
        Sets the task_id of this WFTask.

        :param task_id: The task_id of this WFTask.
        :type: int
        """

        self._task_id = task_id

    @property
    def name(self):
        """
        Gets the name of this WFTask.

        :return: The name of this WFTask.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this WFTask.

        :param name: The name of this WFTask.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this WFTask.

        :return: The description of this WFTask.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this WFTask.

        :param description: The description of this WFTask.
        :type: str
        """

        self._description = description

    @property
    def transition_list(self):
        """
        Gets the transition_list of this WFTask.

        :return: The transition_list of this WFTask.
        :rtype: list[str]
        """
        return self._transition_list

    @transition_list.setter
    def transition_list(self, transition_list):
        """
        Sets the transition_list of this WFTask.

        :param transition_list: The transition_list of this WFTask.
        :type: list[str]
        """

        self._transition_list = transition_list

    @property
    def type(self):
        """
        Gets the type of this WFTask.

        :return: The type of this WFTask.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this WFTask.

        :param type: The type of this WFTask.
        :type: str
        """

        self._type = type

    @property
    def entity_id(self):
        """
        Gets the entity_id of this WFTask.

        :return: The entity_id of this WFTask.
        :rtype: int
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """
        Sets the entity_id of this WFTask.

        :param entity_id: The entity_id of this WFTask.
        :type: int
        """

        self._entity_id = entity_id

    @property
    def due_date(self):
        """
        Gets the due_date of this WFTask.

        :return: The due_date of this WFTask.
        :rtype: datetime
        """
        return self._due_date

    @due_date.setter
    def due_date(self, due_date):
        """
        Sets the due_date of this WFTask.

        :param due_date: The due_date of this WFTask.
        :type: datetime
        """

        self._due_date = due_date

    @property
    def attributes(self):
        """
        Gets the attributes of this WFTask.

        :return: The attributes of this WFTask.
        :rtype: str
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """
        Sets the attributes of this WFTask.

        :param attributes: The attributes of this WFTask.
        :type: str
        """

        self._attributes = attributes

    @property
    def entity(self):
        """
        Gets the entity of this WFTask.

        :return: The entity of this WFTask.
        :rtype: object
        """
        return self._entity

    @entity.setter
    def entity(self, entity):
        """
        Sets the entity of this WFTask.

        :param entity: The entity of this WFTask.
        :type: object
        """

        self._entity = entity

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
