# coding: utf-8

"""
    Stakeholder engagement API

    This API enables Intelligent Engagement for your Business. iEngage is a platform that combines process, augmented intelligence and rewards to help you intelligently engage customers.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MediaType(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, subtype=None, parameters=None, wildcard_type=False, wildcard_subtype=False):
        """
        MediaType - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'subtype': 'str',
            'parameters': 'dict(str, str)',
            'wildcard_type': 'bool',
            'wildcard_subtype': 'bool'
        }

        self.attribute_map = {
            'type': 'type',
            'subtype': 'subtype',
            'parameters': 'parameters',
            'wildcard_type': 'wildcardType',
            'wildcard_subtype': 'wildcardSubtype'
        }

        self._type = type
        self._subtype = subtype
        self._parameters = parameters
        self._wildcard_type = wildcard_type
        self._wildcard_subtype = wildcard_subtype

    @property
    def type(self):
        """
        Gets the type of this MediaType.

        :return: The type of this MediaType.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this MediaType.

        :param type: The type of this MediaType.
        :type: str
        """

        self._type = type

    @property
    def subtype(self):
        """
        Gets the subtype of this MediaType.

        :return: The subtype of this MediaType.
        :rtype: str
        """
        return self._subtype

    @subtype.setter
    def subtype(self, subtype):
        """
        Sets the subtype of this MediaType.

        :param subtype: The subtype of this MediaType.
        :type: str
        """

        self._subtype = subtype

    @property
    def parameters(self):
        """
        Gets the parameters of this MediaType.

        :return: The parameters of this MediaType.
        :rtype: dict(str, str)
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """
        Sets the parameters of this MediaType.

        :param parameters: The parameters of this MediaType.
        :type: dict(str, str)
        """

        self._parameters = parameters

    @property
    def wildcard_type(self):
        """
        Gets the wildcard_type of this MediaType.

        :return: The wildcard_type of this MediaType.
        :rtype: bool
        """
        return self._wildcard_type

    @wildcard_type.setter
    def wildcard_type(self, wildcard_type):
        """
        Sets the wildcard_type of this MediaType.

        :param wildcard_type: The wildcard_type of this MediaType.
        :type: bool
        """

        self._wildcard_type = wildcard_type

    @property
    def wildcard_subtype(self):
        """
        Gets the wildcard_subtype of this MediaType.

        :return: The wildcard_subtype of this MediaType.
        :rtype: bool
        """
        return self._wildcard_subtype

    @wildcard_subtype.setter
    def wildcard_subtype(self, wildcard_subtype):
        """
        Sets the wildcard_subtype of this MediaType.

        :param wildcard_subtype: The wildcard_subtype of this MediaType.
        :type: bool
        """

        self._wildcard_subtype = wildcard_subtype

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
